name: CI

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest black isort ruff mypy pre-commit types-PyYAML

      - name: Run pytest
        run: pytest

      - name: Check formatting with black
        run: black --check schemarize tests

      - name: Check import sorting with isort
        run: isort --check-only schemarize tests

      - name: Lint with ruff
        run: ruff check schemarize tests

      - name: Type check with mypy
        run: mypy schemarize
